[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Configure secrets scanning to ignore specific files
  SECRETS_SCAN_OMIT_PATHS = "PRODUCTION_DEBUG_GUIDE.md,debug.html,dist/assets/*.js"
